language: node_js
node_js:
  - "node"
after_script:
  - npm install -g istanbul nodeunit && npm install codecov.io
  - istanbul cover nodeunit ./test.js -- --reporter lcov && cat ./coverage/coverage.json | ./node_modules/codecov.io/bin/codecov.io.js